var Tooltips = new Map();

Tooltips.set("AZCW",                  "All Zero Code Words");
Tooltips.set("AWGN",                  "Additive White Gaussian Noise");
Tooltips.set("BEC",                   "Binary Erasure Channel");
Tooltips.set("BSC",                   "Binary Symmetric Channel");
Tooltips.set("PSK",                   "Phase-Shift Keying");
Tooltips.set("QAM",                   "Quadrature Amplitude Modulation");
Tooltips.set("PAM",                   "Pulse-Amplitude Modulation");
Tooltips.set("OOK",                   "On-Off Keying");
Tooltips.set("CPM",                   "Continuous Phase Modulation");
Tooltips.set("SCMA",                  "Sparse Code Multiple Access");
Tooltips.set("BPSK",                  "Bit Phase-Shift Keying");
Tooltips.set("ML",                    "Maximum Likelihood");
Tooltips.set("BP",                    "Belief Propagation");
Tooltips.set("BP_LAYERED",            "Belief Propagation with horizontal layered scheduling");
Tooltips.set("BP_HORIZONTAL_LAYERED", "Belief Propagation with horizontal layered scheduling");
Tooltips.set("BP_VERTICAL_LAYERED",   "Belief Propagation with vertical layered scheduling");
Tooltips.set("BP_FLOODING",           "Belief Propagation with flooding scheduling");
Tooltips.set("SPA",                   "Sum-Product Algorithm");
Tooltips.set("LSPA",                  "Logarithm Sum-Product Algorithm");
Tooltips.set("MS",                    "Min-Sum");
Tooltips.set("NMS",                   "Normalized Min-Sum");
Tooltips.set("OMS",                   "Offset Min-Sum");
Tooltips.set("ONMS",                  "Offset Normalized Min-Sum");
Tooltips.set("AMS",                   "Approximate Min-Star");
Tooltips.set("GALA",                  "Gallager A");
Tooltips.set("ASCL",                  "Adaptive Successive Cancellation List");
Tooltips.set("SC",                    "Successive Cancellation");
Tooltips.set("SCL",                   "Successive Cancellation List");
Tooltips.set("SCAN",                  "Soft CANcellation");
Tooltips.set("CP",                    "Chase-Pyndiah");
Tooltips.set("BCJR",                  "Bahl, Cocke, Jelinek and Raviv algorithm or Maximum A Posteriori (MAP)");
Tooltips.set("BFER",                  "Bit/Frame Error Rate");
Tooltips.set("BFERI",                 "Bit/Frame Error Rate Iterative (turbo demodulation)");
Tooltips.set("EXIT",                  "EXtrinsic Information Transfer chart");
Tooltips.set("ARP",                   "Almost Regular Permutation");
Tooltips.set("CCSDS",                 "Consultative Committee for Space Data Systems");
Tooltips.set("LTE",                   "Long Term Evolution");
Tooltips.set("GSM",                   "Global System for Mobile Communications");
Tooltips.set("DVB-S1",                "Digital Video Broadcasting - Satellite 1");
Tooltips.set("DVB-S2",                "Digital Video Broadcasting - Satellite 2");
Tooltips.set("DVB-RCS1",              "Digital Video Broadcasting - Return Channel via Satellite 1");
Tooltips.set("DVB-RCS2",              "Digital Video Broadcasting - Return Channel via Satellite 2");
Tooltips.set("STD",                   "Standard");
Tooltips.set("RAND",                  "Random");
Tooltips.set("POW2",                  "Distance between the quantified values is a power of 2");
Tooltips.set("CUSTOM",                "Distance between the quantified values is customized");
Tooltips.set("LDPC",                  "Low-Density Parity-Check code");
Tooltips.set("BCH",                   "Bose, Ray-Chaudhuri and Hocquenghem code");
Tooltips.set("RS",                    "Reed-Solomon code");
Tooltips.set("RSC",                   "Recursive Systematic Convolutional code");
Tooltips.set("REP",                   "Repetition code");
Tooltips.set("RA",                    "Repeat and Accumulate code");
Tooltips.set("POLAR",                 "Polar code");
Tooltips.set("TURBO",                 "Parallel Turbo code (Single-Binary)");
Tooltips.set("TURBO_DB",              "Parallel Turbo code (Double-Binary)");
Tooltips.set("TURBO_PROD",            "Turbo Product code");
Tooltips.set("UNCODED",               "No channel code");
Tooltips.set("ROW_COL",               "Row Column");
Tooltips.set("TPC",                   "Turbo Product Code");
