var mapDef = new Map();

mapDef.set("AZCW",        "All Zero Code Words");
mapDef.set("AWGN",        "Additive White Gaussian Noise");
mapDef.set("PSK",         "Phase-Shift Keying");
mapDef.set("QAM",         "Quadrature Amplitude Modulation");
mapDef.set("PAM",         "Pulse-Amplitude Modulation");
mapDef.set("OOK",         "On-Off Keying");
mapDef.set("CPM",         "Continuous Phase Modulation");
mapDef.set("SCMA",        "Sparse Code Multiple Access");
mapDef.set("BPSK",        "Bit Phase-Shift Keying");
mapDef.set("BCH",         "Bose, Ray-Chaudhuri and Hocquenghem code");
mapDef.set("LDPC",        "Low-Density Parity-Check");
mapDef.set("RSC",         "Recursive Systematic Convolutional");
mapDef.set("REP",         "Repetition");
mapDef.set("RA",          "Repeat and Accumulate");
mapDef.set("ML",          "Maximum Likelihood");
mapDef.set("BP",          "Belief Propagation");
mapDef.set("BP_LAYERED",  "Belief Propagation with horizontal layered scheduling");
mapDef.set("BP_FLOODING", "Belief Propagation with flooding scheduling");
mapDef.set("SPA",         "Sum-Product Algorithm");
mapDef.set("LSPA",        "Logarithm Sum-Product Algorithm");
mapDef.set("MS",          "Min-Sum");
mapDef.set("NMS",         "Normalized Min-Sum");
mapDef.set("OMS",         "Offset Min-Sum");
mapDef.set("ONMS",        "Offset Normalized Min-Sum");
mapDef.set("AMS",         "Approximate Min-Star");
mapDef.set("GALA",        "Gallager A");
mapDef.set("ASCL",        "Adaptive Successive Cancellation List");
mapDef.set("SC",          "Successive Cancellation");
mapDef.set("SCL",         "Successive Cancellation List");
mapDef.set("SCAN",        "Soft CANcellation");
mapDef.set("BCJR",        "Bahl, Cocke, Jelinek and Raviv algorithm");
mapDef.set("BFER",        "Bit/Frame Error Rate");
mapDef.set("BFERI",       "Bit/Frame Error Rate Iterative (turbo demodulation)");
mapDef.set("EXIT",        "EXtrinsic Information Transfer chart");
mapDef.set("ARP",         "Almost Regular Permutation");
mapDef.set("CCSDS",       "Consultative Committee for Space Data Systems");
mapDef.set("LTE",         "Long Term Evolution");
mapDef.set("GSM",         "Global System for Mobile Communications");
mapDef.set("DVB-S1",      "Digital Video Broadcasting - Satellite 1");
mapDef.set("DVB-S2",      "Digital Video Broadcasting - Satellite 2");
mapDef.set("DVB-RCS1",    "Digital Video Broadcasting - Return Channel via Satellite 1");
mapDef.set("DVB-RCS2",    "Digital Video Broadcasting - Return Channel via Satellite 2");
mapDef.set("STD",         "Standard");