var tooltips = new Map();

tooltips.set("AZCW",        "All Zero Code Words");
tooltips.set("AWGN",        "Additive White Gaussian Noise");
tooltips.set("PSK",         "Phase-Shift Keying");
tooltips.set("QAM",         "Quadrature Amplitude Modulation");
tooltips.set("PAM",         "Pulse-Amplitude Modulation");
tooltips.set("OOK",         "On-Off Keying");
tooltips.set("CPM",         "Continuous Phase Modulation");
tooltips.set("SCMA",        "Sparse Code Multiple Access");
tooltips.set("BPSK",        "Bit Phase-Shift Keying");
tooltips.set("BCH",         "Bose, Ray-Chaudhuri and Hocquenghem code");
tooltips.set("LDPC",        "Low-Density Parity-Check");
tooltips.set("RSC",         "Recursive Systematic Convolutional");
tooltips.set("REP",         "Repetition");
tooltips.set("RA",          "Repeat and Accumulate");
tooltips.set("ML",          "Maximum Likelihood");
tooltips.set("BP",          "Belief Propagation");
tooltips.set("BP_LAYERED",  "Belief Propagation with horizontal layered scheduling");
tooltips.set("BP_FLOODING", "Belief Propagation with flooding scheduling");
tooltips.set("SPA",         "Sum-Product Algorithm");
tooltips.set("LSPA",        "Logarithm Sum-Product Algorithm");
tooltips.set("MS",          "Min-Sum");
tooltips.set("NMS",         "Normalized Min-Sum");
tooltips.set("OMS",         "Offset Min-Sum");
tooltips.set("ONMS",        "Offset Normalized Min-Sum");
tooltips.set("AMS",         "Approximate Min-Star");
tooltips.set("GALA",        "Gallager A");
tooltips.set("ASCL",        "Adaptive Successive Cancellation List");
tooltips.set("SC",          "Successive Cancellation");
tooltips.set("SCL",         "Successive Cancellation List");
tooltips.set("SCAN",        "Soft CANcellation");
tooltips.set("BCJR",        "Bahl, Cocke, Jelinek and Raviv algorithm");
tooltips.set("BFER",        "Bit/Frame Error Rate");
tooltips.set("BFERI",       "Bit/Frame Error Rate Iterative (turbo demodulation)");
tooltips.set("EXIT",        "EXtrinsic Information Transfer chart");
tooltips.set("ARP",         "Almost Regular Permutation");
tooltips.set("CCSDS",       "Consultative Committee for Space Data Systems");
tooltips.set("LTE",         "Long Term Evolution");
tooltips.set("GSM",         "Global System for Mobile Communications");
tooltips.set("DVB-S1",      "Digital Video Broadcasting - Satellite 1");
tooltips.set("DVB-S2",      "Digital Video Broadcasting - Satellite 2");
tooltips.set("DVB-RCS1",    "Digital Video Broadcasting - Return Channel via Satellite 1");
tooltips.set("DVB-RCS2",    "Digital Video Broadcasting - Return Channel via Satellite 2");
tooltips.set("STD",         "Standard");